"use client";

import { useState } from "react";
import type { RoasterJobView } from "./types";
import { formatScore } from "@/lib/roaster/formatScore";

type RewritesTabProps = {
  job: RoasterJobView;
};

export function RewritesTab({ job }: RewritesTabProps) {
  const { listingData, listingScore } = job;
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const flash = (key: string) => {
    setCopiedKey(key);
    window.setTimeout(() => setCopiedKey(null), 2000);
  };

  const copyText = async (key: string, text: string) => {
    await navigator.clipboard.writeText(text);
    flash(key);
  };

  const title = listingData.title;
  const bullets = listingData.bulletPoints;
  const desc = listingData.description;

  const copyAll = async () => {
    const lines = [
      `LISTING REWRITES — ${title}`,
      "Generated by Pixii Roaster",
      "",
      "TITLE:",
      listingScore.titleRewrite,
      "",
      "BULLET POINTS:",
      ...listingScore.bulletRewrites.map((b, i) => `${i + 1}. ${b}`),
      "",
      "DESCRIPTION OPENING:",
      listingScore.descriptionRewrite,
    ];
    await copyText("all", lines.join("\n"));
  };

  const titleWords = title.trim().split(/\s+/).filter(Boolean).length;

  return (
    <div className="space-y-8">
      <p className="text-sm text-neutral-600">
        These are Claude&apos;s suggested rewrites based on your score. Copy and
        test them.
      </p>

      <section>
        <h3 className="font-heading text-base font-semibold text-black">
          📝 Title Rewrite
        </h3>
        <div className="mt-3 grid gap-4 md:grid-cols-2">
          <div className="rounded-xl border border-neutral-200 bg-white p-4 shadow-sm">
            <p className="text-xs font-semibold text-neutral-500">Current Title</p>
            <p className="mt-2 text-sm text-neutral-800">{title}</p>
            <p className={`mt-2 text-xs font-semibold ${formatScore(listingScore.titleScore)}`}>
              Score: {listingScore.titleScore}/100
            </p>
            <p className="mt-1 text-xs text-red-800/90">
              Issues: {listingScore.titleIssues.join(", ") || "—"}
            </p>
            <p className="mt-2 text-xs text-neutral-500">
              {titleWords} words · {title.length} characters
            </p>
          </div>
          <div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-4 shadow-sm">
            <p className="text-xs font-semibold text-emerald-900">Suggested Rewrite</p>
            <p className="mt-2 text-sm text-neutral-900">
              {listingScore.titleRewrite}
            </p>
            <p className="mt-2 text-xs text-neutral-500">
              {listingScore.titleRewrite.length} characters
            </p>
            <button
              type="button"
              onClick={() => void copyText("title", listingScore.titleRewrite)}
              className="mt-3 rounded-lg border border-emerald-300 bg-white px-3 py-1.5 text-xs font-semibold text-emerald-900 hover:bg-emerald-50"
            >
              {copiedKey === "title" ? "Copied!" : "Copy Rewrite"}
            </button>
          </div>
        </div>
      </section>

      <section>
        <h3 className="font-heading text-base font-semibold text-black">
          📋 Bullet Point Rewrites
        </h3>
        <div className="mt-3 space-y-4">
          {bullets.map((b, i) => {
            const rw = listingScore.bulletRewrites[i];
            const key = `b-${i}`;
            return (
              <div
                key={i}
                className="grid gap-3 rounded-xl border border-neutral-200 bg-white p-4 shadow-sm md:grid-cols-2"
              >
                <div>
                  <p className="text-xs font-semibold text-neutral-500">Original</p>
                  <p className="mt-1 text-sm text-neutral-600">{b}</p>
                </div>
                <div className="rounded-lg border border-emerald-200 bg-emerald-50/50 p-3">
                  {rw ? (
                    <>
                      <p className="text-sm text-neutral-900">{rw}</p>
                      <button
                        type="button"
                        onClick={() => void copyText(key, rw)}
                        className="mt-2 text-xs font-semibold text-primary hover:underline"
                      >
                        {copiedKey === key ? "Copied!" : "Copy"}
                      </button>
                    </>
                  ) : (
                    <p className="text-sm text-emerald-800/80">
                      Bullet looks solid — keep as is
                    </p>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </section>

      <section>
        <h3 className="font-heading text-base font-semibold text-black">
          📄 Description Rewrite
        </h3>
        <div className="mt-3 grid gap-4 md:grid-cols-2">
          <div className="rounded-xl border border-neutral-200 bg-white p-4 shadow-sm">
            <p className="text-xs font-semibold text-neutral-500">Current Opening</p>
            <p className="mt-2 text-sm text-neutral-600">
              {desc.slice(0, 300)}
              {desc.length > 300 ? "…" : ""}
            </p>
          </div>
          <div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-4 shadow-sm">
            <p className="text-xs font-semibold text-emerald-900">Suggested Opening</p>
            <p className="mt-2 text-sm text-neutral-900">
              {listingScore.descriptionRewrite}
            </p>
            <button
              type="button"
              onClick={() =>
                void copyText("desc", listingScore.descriptionRewrite)
              }
              className="mt-3 rounded-lg border border-emerald-300 bg-white px-3 py-1.5 text-xs font-semibold text-emerald-900 hover:bg-emerald-50"
            >
              {copiedKey === "desc" ? "Copied!" : "Copy Rewrite"}
            </button>
          </div>
        </div>
      </section>

      <button
        type="button"
        onClick={() => void copyAll()}
        className="w-full rounded-lg border border-neutral-200 bg-white px-4 py-3 text-sm font-semibold text-neutral-800 shadow-sm hover:bg-neutral-50"
      >
        {copiedKey === "all" ? "Copied!" : "Copy All Rewrites"}
      </button>
    </div>
  );
}
