"use client";

import { useState } from "react";
import type { RoasterJobView } from "./types";
import { formatScore } from "@/lib/roaster/formatScore";

type RewritesTabProps = {
  job: RoasterJobView;
};

const card =
  "rounded-xl border border-border/80 bg-card/95 shadow-sm ring-1 ring-black/[0.03] backdrop-blur-[1px] dark:ring-white/[0.05]";

const emeraldPanel =
  "rounded-xl border border-emerald-200/90 bg-emerald-50/70 p-4 shadow-sm dark:border-emerald-500/30 dark:bg-emerald-950/25";

const copyRewriteBtn =
  "mt-3 rounded-lg border border-emerald-300/90 bg-card px-3 py-1.5 text-xs font-semibold text-emerald-900 shadow-sm ring-1 ring-black/[0.04] transition-colors hover:bg-emerald-50/80 dark:border-emerald-500/40 dark:bg-card dark:text-emerald-100 dark:hover:bg-emerald-950/40 dark:ring-white/[0.06]";

const secondaryFull =
  "w-full rounded-lg border border-border bg-card px-4 py-3 text-sm font-semibold text-foreground shadow-sm ring-1 ring-black/[0.04] transition-colors hover:bg-muted dark:ring-white/[0.06]";

export function RewritesTab({ job }: RewritesTabProps) {
  const { listingData, listingScore } = job;
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const flash = (key: string) => {
    setCopiedKey(key);
    window.setTimeout(() => setCopiedKey(null), 2000);
  };

  const copyText = async (key: string, text: string) => {
    await navigator.clipboard.writeText(text);
    flash(key);
  };

  const title = listingData.title;
  const bullets = listingData.bulletPoints;
  const desc = listingData.description;

  const copyAll = async () => {
    const lines = [
      `LISTING REWRITES — ${title}`,
      "Generated by Pixii Roaster",
      "",
      "TITLE:",
      listingScore.titleRewrite,
      "",
      "BULLET POINTS:",
      ...listingScore.bulletRewrites.map((b, i) => `${i + 1}. ${b}`),
      "",
      "DESCRIPTION OPENING:",
      listingScore.descriptionRewrite,
    ];
    await copyText("all", lines.join("\n"));
  };

  const titleWords = title.trim().split(/\s+/).filter(Boolean).length;

  return (
    <div className="space-y-8">
      <p className="text-sm text-muted-foreground">
        These are Claude&apos;s suggested rewrites based on your score. Copy and
        test them.
      </p>

      <section>
        <h3 className="font-heading text-base font-semibold text-foreground">
          Title rewrite
        </h3>
        <div className="mt-3 grid gap-4 md:grid-cols-2">
          <div className={`${card} p-4`}>
            <p className="text-xs font-semibold text-muted-foreground">Current title</p>
            <p className="mt-2 text-sm text-foreground">{title}</p>
            <p className={`mt-2 text-xs font-semibold ${formatScore(listingScore.titleScore)}`}>
              Score: {listingScore.titleScore}/100
            </p>
            <p className="mt-1 text-xs text-red-800/90 dark:text-red-300">
              Issues: {listingScore.titleIssues.join(", ") || "—"}
            </p>
            <p className="mt-2 text-xs text-muted-foreground">
              {titleWords} words · {title.length} characters
            </p>
          </div>
          <div className={emeraldPanel}>
            <p className="text-xs font-semibold text-emerald-900 dark:text-emerald-200">
              Suggested rewrite
            </p>
            <p className="mt-2 text-sm text-foreground">{listingScore.titleRewrite}</p>
            <p className="mt-2 text-xs text-muted-foreground">
              {listingScore.titleRewrite.length} characters
            </p>
            <button
              type="button"
              onClick={() => void copyText("title", listingScore.titleRewrite)}
              className={copyRewriteBtn}
            >
              {copiedKey === "title" ? "Copied!" : "Copy rewrite"}
            </button>
          </div>
        </div>
      </section>

      <section>
        <h3 className="font-heading text-base font-semibold text-foreground">
          Bullet point rewrites
        </h3>
        <div className="mt-3 space-y-4">
          {bullets.map((b, i) => {
            const rw = listingScore.bulletRewrites[i];
            const key = `b-${i}`;
            return (
              <div key={i} className={`grid gap-3 md:grid-cols-2 ${card} p-4`}>
                <div>
                  <p className="text-xs font-semibold text-muted-foreground">Original</p>
                  <p className="mt-1 text-sm text-muted-foreground">{b}</p>
                </div>
                <div className="rounded-lg border border-emerald-200/80 bg-emerald-50/50 p-3 dark:border-emerald-500/25 dark:bg-emerald-950/20">
                  {rw ? (
                    <>
                      <p className="text-sm text-foreground">{rw}</p>
                      <button
                        type="button"
                        onClick={() => void copyText(key, rw)}
                        className="mt-2 text-xs font-semibold text-primary hover:underline"
                      >
                        {copiedKey === key ? "Copied!" : "Copy"}
                      </button>
                    </>
                  ) : (
                    <p className="text-sm text-emerald-800/90 dark:text-emerald-300">
                      Bullet looks solid — keep as is
                    </p>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </section>

      <section>
        <h3 className="font-heading text-base font-semibold text-foreground">
          Description rewrite
        </h3>
        <div className="mt-3 grid gap-4 md:grid-cols-2">
          <div className={`${card} p-4`}>
            <p className="text-xs font-semibold text-muted-foreground">Current opening</p>
            <p className="mt-2 text-sm text-muted-foreground">
              {desc.slice(0, 300)}
              {desc.length > 300 ? "…" : ""}
            </p>
          </div>
          <div className={emeraldPanel}>
            <p className="text-xs font-semibold text-emerald-900 dark:text-emerald-200">
              Suggested opening
            </p>
            <p className="mt-2 text-sm text-foreground">{listingScore.descriptionRewrite}</p>
            <button
              type="button"
              onClick={() => void copyText("desc", listingScore.descriptionRewrite)}
              className={copyRewriteBtn}
            >
              {copiedKey === "desc" ? "Copied!" : "Copy rewrite"}
            </button>
          </div>
        </div>
      </section>

      <button type="button" onClick={() => void copyAll()} className={secondaryFull}>
        {copiedKey === "all" ? "Copied!" : "Copy all rewrites"}
      </button>
    </div>
  );
}
