"use client";

import type { MarketJob } from "./types";

type AIInsightsTabProps = {
  job: MarketJob;
};

export function AIInsightsTab({ job }: AIInsightsTabProps) {
  const m = job.marketAnalysis;
  const gaps = m.opportunityGaps.slice(0, 3);
  const trends = m.marketTrends.slice(0, 3);

  return (
    <div className="space-y-6">
      <div className="rounded-xl border-l-4 border-primary bg-primary/[0.06] p-4 shadow-sm">
        <p className="text-xs font-semibold uppercase tracking-wide text-primary">
          💡 Key Insight
        </p>
        <p className="mt-2 text-lg font-medium leading-relaxed text-neutral-900">
          <span className="mr-1 text-2xl text-primary/40" aria-hidden>
            &ldquo;
          </span>
          {m.keyInsight || "—"}
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div>
          <p className="text-sm font-semibold text-black">
            🚀 Opportunity Gaps
          </p>
          <p className="text-xs text-neutral-500">Where new products can win</p>
          <ul className="mt-3 space-y-2">
            {gaps.map((g, i) => (
              <li
                key={i}
                className="rounded-lg border border-emerald-100 bg-emerald-50/80 px-3 py-2.5 text-sm text-neutral-800"
              >
                <span className="mr-2 inline-flex size-6 items-center justify-center rounded-full bg-emerald-200 text-xs font-bold text-emerald-900">
                  {i + 1}
                </span>
                {g}
              </li>
            ))}
          </ul>
        </div>
        <div>
          <p className="text-sm font-semibold text-black">📈 Market Trends</p>
          <p className="text-xs text-neutral-500">What&apos;s driving this market</p>
          <ul className="mt-3 space-y-2">
            {trends.map((t, i) => (
              <li
                key={i}
                className="rounded-lg border border-sky-100 bg-sky-50/80 px-3 py-2.5 text-sm text-neutral-800"
              >
                <span className="mr-1.5" aria-hidden>
                  📈
                </span>
                {t}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="rounded-xl border border-neutral-200 bg-white p-4 shadow-sm ring-1 ring-neutral-100">
        <p className="text-sm font-semibold text-black">
          🗺️ Recommended Entry Strategy
        </p>
        <p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-neutral-800">
          {m.entryStrategy || "—"}
        </p>
        <p className="mt-3 text-[11px] text-neutral-500">
          Strategy generated by Claude based on the top 10 market data
        </p>
      </div>

      <p className="text-[11px] text-neutral-500">
        * Estimates based on Best Sellers Rank position. For directional research only.
      </p>
    </div>
  );
}
